// DropdownValues.js

const ivRemarksDropdownOptions = [
  { id: 1, ivRemarks: "Already done in same month" },
  { id: 2, ivRemarks: "Appt Cancelled" },
  { id: 3, ivRemarks: "Discounted Plan" },
  { id: 4, ivRemarks: "Benefit maxed out as per ES" },
  { id: 5, ivRemarks: "Benefit Response not Received" },
  { id: 6, ivRemarks: "Benefits not available on web" },
  { id: 7, ivRemarks: "Call insurance for policy holder" },
  { id: 8, ivRemarks: "Cash Patient - office" },
  { id: 9, ivRemarks: "Cash Patient - PI Team" },
  { id: 10, ivRemarks: "Completed" },
  { id: 11, ivRemarks: "Completed as Per Recall/Contx Workfow" },
  { id: 12, ivRemarks: "Coverage book Not available (HMO) (Day Team)" },
  { id: 13, ivRemarks: "Database Not Available (Day Team)" },
  { id: 14, ivRemarks: "Dependent not enrolled" },
  { id: 15, ivRemarks: "Emailed To Beam" },
  { id: 16, ivRemarks: "Fax not received" },
  { id: 17, ivRemarks: "Faxback Attached in SD" },
  { id: 18, ivRemarks: "Future activation date" },
  { id: 19, ivRemarks: "Inactive" },
  { id: 20, ivRemarks: "INCOMPLETE - Night IV needs to call for Benefits" },
  { id: 21, ivRemarks: "INCOMPLETE - Office needs to call for Benefits" },
  {
    id: 22,
    ivRemarks: "INCOMPLETE - Office needs to call for Benefits & History",
  },
  { id: 23, ivRemarks: "INCOMPLETE - Office needs to call for History" },
  { id: 24, ivRemarks: "Incomplete Information" },
  { id: 25, ivRemarks: "Ineligible" },
  { id: 26, ivRemarks: "Maintenance in Portal (Day Team)" },
  { id: 27, ivRemarks: "Maxed Out" },
  { id: 28, ivRemarks: "Medicaid IVs (Day Team)" },
  { id: 29, ivRemarks: "Medicaid IVs for Future Dates (Day Team)" },
  { id: 30, ivRemarks: "Medical Policy" },
  { id: 31, ivRemarks: "Missing Insurance Details" },
  { id: 32, ivRemarks: "No Dental Coverage" },
  { id: 33, ivRemarks: "No OON Benefits" },
  { id: 34, ivRemarks: "No OS Benefits" },
  { id: 35, ivRemarks: "Not able to contact with rep" },
  { id: 36, ivRemarks: "Not assigned to our office" },
  { id: 37, ivRemarks: "Not Found over Call" },
  { id: 38, ivRemarks: "office Closed" },
  { id: 39, ivRemarks: "Office denied to do the IV" },
  { id: 40, ivRemarks: "Only Ortho IV required as per ofc" },
  { id: 41, ivRemarks: "Only OS IV required as per ofc" },
  { id: 42, ivRemarks: "OS Patient" },
  { id: 43, ivRemarks: "Indemnity plan" },
  { id: 44, ivRemarks: "PCS Not Available (HMO) (Day Team)" },
  { id: 45, ivRemarks: "Pediatric Plan" },
  { id: 46, ivRemarks: "Policy Cancelled" },
  { id: 47, ivRemarks: "Portal Not Available (Day Team)" },
  { id: 48, ivRemarks: "Portal Not Working (Day Team)" },
  { id: 49, ivRemarks: "Previous Month" },
  { id: 50, ivRemarks: "Rep denied to provide info" },
  { id: 51, ivRemarks: "Repeated" },
  { id: 52, ivRemarks: "Return to Office" },
  { id: 53, ivRemarks: "Rush not Accepted" },
  { id: 54, ivRemarks: "Technical Issues" },
  { id: 55, ivRemarks: "Terminated" },
  { id: 56, ivRemarks: "Third party Issue - Office need to call" },
  { id: 57, ivRemarks: "To be done by Office" },
  { id: 58, ivRemarks: "To be Started" },
  { id: 59, ivRemarks: "Unable to retrive information" },
  { id: 60, ivRemarks: "Wrong information" },
  { id: 61, ivRemarks: "Provider not available on Provider Schedule" },
  { id: 62, ivRemarks: "Not Found over web, Night IV need to call" },
  { id: 63, ivRemarks: "Not found on web and call" },
  { id: 64, ivRemarks: "Not accepting HMO patient" },
  { id: 65, ivRemarks: "Completed, Not updated in ES, IV emailed" },
  { id: 66, ivRemarks: "Missing Insurance Details, No info ES" },
  { id: 67, ivRemarks: "Not Found over web" },
  { id: 68, ivRemarks: "Ortho/OS Provider on Scheduler" },
  { id: 69, ivRemarks: "IV Return - TX on Exchange above 18 years" },
  {
    id: 70,
    ivRemarks: "Office Is closed for the day, Patient need to reschedule.",
  },
  { id: 71, ivRemarks: "Faxback Attached in Drive" },
  { id: 72, ivRemarks: "Completed, Not assigned to Facility" },
  { id: 73, ivRemarks: "Technical Issue - Not received OTP/Fax" },
  { id: 74, ivRemarks: "Unable to check Provider/Facility Status" },
  { id: 75, ivRemarks: "Updated ES, IV has not created" },
  { id: 76, ivRemarks: "IV not created, Email sent for benefits" },
];

const sourceDropdownOptions = [
  { id: 1, source: "DB" },
  { id: 2, source: "DB + Call" },
  { id: 3, source: "DB + Web" },
  { id: 4, source: "DB + Fax" },
  { id: 5, source: "DB + Fax + Web" },
  { id: 6, source: "DB + Fax + Call" },
  { id: 7, source: "DB + Web + Call" },
  { id: 8, source: "Fax + DB + Web + Call" },
  { id: 9, source: "Call" },
  { id: 10, source: "Website" },
  { id: 11, source: "Fax" },
  { id: 12, source: "MDB" },
  { id: 13, source: "MDB + Call" },
  { id: 14, source: "MDB + Web" },
  { id: 15, source: "MDB + Fax" },
  { id: 16, source: "MDB + Fax + Call" },
  { id: 17, source: "MDB + Web + Call" },
  { id: 18, source: "Fax + MDB + Web + Call" },
  { id: 19, source: "Call + Web" },
  { id: 20, source: "Scraping Tool" },
  { id: 21, source: "MDB + Web + Call" },
  { id: 22, source: "Fax + Web" },
  { id: 23, source: "Fax + Call" },
  { id: 24, source: "Scraping + Web + Call" },
  { id: 25, source: "Scraping Tool + Web" },
  { id: 26, source: "RTE + DB" },
  { id: 27, source: "RTE + Call" },
  { id: 28, source: "RTE + Web" },
  { id: 29, source: "RTE + MDB + Call" },
  { id: 30, source: "RTE + MDB" },
  { id: 31, source: "BaseTemplate" },
  { id: 32, source: "BaseTemplate + Web" },
  { id: 33, source: "BaseTemplate + Call" },
  { id: 34, source: "DB + Chat" },
  { id: 35, source: "DB + Web + Chat" },
  { id: 36, source: "Web + Chat" },
  { id: 37, source: "MDB + Web + Chat" },
  { id: 38, source: "MDB + Chat" },
  { id: 39, source: "Call + Chat" },
];

const planTypeDropdownOptions = [
  { id: 1, planType: "Child Medicaid" },
  { id: 2, planType: "Medicare" },
  { id: 3, planType: "PPO" },
  { id: 4, planType: "HMO" },
  { id: 5, planType: "EPO" },
  { id: 6, planType: "DDPO" },
  { id: 7, planType: "Indemnity" },
  { id: 8, planType: "Adult Medicaid" },
  { id: 9, planType: "Discounted Plan" },
  { id: 10, planType: "INO" },
  { id: 11, planType: "Medical Policy" },
  { id: 12, planType: "Standard" },
  { id: 13, planType: "Self Funded" },
  { id: 14, planType: "Texas Medicare Medicaid" },
  { id: 15, planType: "Pediatric Plan" },
  { id: 16, planType: "PPO (OUT)" },
  { id: 17, planType: "HMO Medicare" },
];

const officeNames = [
  { id: 1, officeName: "Aransas" },
  { id: 2, officeName: "Azle" },
  { id: 3, officeName: "Beaumont" },
  { id: 4, officeName: "Benbrook" },
  { id: 5, officeName: "Calallen" },
  { id: 6, officeName: "Crosby" },
  { id: 7, officeName: "Devine" },
  { id: 8, officeName: "Elgin" },
  { id: 9, officeName: "Grangerland" },
  { id: 10, officeName: "Huffman" },
  { id: 11, officeName: "Jasper" },
  { id: 12, officeName: "Lavaca" },
  { id: 13, officeName: "Liberty" },
  { id: 14, officeName: "Lytle" },
  { id: 15, officeName: "Mathis" },
  { id: 16, officeName: "Potranco" },
  { id: 17, officeName: "Rio Bravo" },
  { id: 18, officeName: "Riverwalk" },
  { id: 19, officeName: "Rockdale" },
  { id: 20, officeName: "Sinton" },
  { id: 21, officeName: "Splendora" },
  { id: 22, officeName: "Springtown" },
  { id: 23, officeName: "Tidwell" },
  { id: 24, officeName: "Victoria" },
  { id: 25, officeName: "Westgreen" },
  { id: 26, officeName: "Winnie" },
  { id: 27, officeName: "OS" },
];

export {
  ivRemarksDropdownOptions,
  sourceDropdownOptions,
  planTypeDropdownOptions,
  officeNames,
};
